plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.14' apply false
    id 'io.spring.dependency-management' version '1.1.6' apply false
}

group = 'com.taxidispatcher'

/**
 * 모든 서브 모듈 공통 설정
 */
subprojects {
    apply plugin: 'java'
    apply plugin: 'org.springframework.boot'
    apply plugin: 'io.spring.dependency-management'

//    group = 'com.taxi.dispatcher'
    version = '1.0.0-SNAPSHOT'

    repositories {
        mavenCentral()
    }

    java {
        sourceCompatibility = '17'
        targetCompatibility = '17'
    }

    /**
     * 공통 의존성
     */
    dependencies {
        // Lombok
        compileOnly 'org.projectlombok:lombok'
        annotationProcessor 'org.projectlombok:lombok'

        // Test
        testImplementation 'org.springframework.boot:spring-boot-starter-test'
        testImplementation 'org.junit.jupiter:junit-jupiter'
    }

    tasks.named('test') {
        useJUnitPlatform()
    }
}