rootProject.name = 'taxi-dispatcher'
include 'shared'
include 'shared:common-lib'
findProject(':shared:common-lib')?.name = 'common-lib'
include 'services'
include 'services:account-service'
findProject(':services:account-service')?.name = 'account-service'
include 'services:customer-service'
findProject(':services:customer-service')?.name = 'customer-service'
include 'services:driver-service'
findProject(':services:driver-service')?.name = 'driver-service'
include 'services:dispatcher-service'
findProject(':services:dispatcher-service')?.name = 'dispatcher-service'

