spring:
  application:
    name: account-service

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC
        format_sql: true
        use_sql_comments: true
    show-sql: false

  jackson:
    default-timezone: UTC
    serialization:
      write-dates-as-timestamps: false

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/account_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: admin
      password: admin123

server:
  port: ${SPRING_SERVER_PORT:8081}
  servlet:
    context-path: /

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
  override-with-generic-response: false

jwt:
  privateKey: ${JWT_PRIVATE_KEY:MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCG4dkf2G8tgRqPZmP97OBgfoeIWZbpC85lH7GLKpNYbL0+AWL1hQRqLbjUjXkoJFuhfYJwsBKItbgwj6X6DMnmfhQ6NiipcGCptZJ1C5slWUBF2tCtBYxzhzqeotup5WXc608fdcYRLx04cck3ROu5omKsoMzB8Y67if66T9AyyjCrT4f1JsfgTrQYKGGQ9BFX4b4XLnMkBbYBlByllpLlammpQmEy2MDVS8nQoJd5yVbcqPgs84929vJcQfSH+JddlUPQdrOxsFj5uQQxWiU5ESVkTlB63bdROGmlMyuQYipvBQswMOkvKtsJv0EyXVQFbvRfPcNAnxNtrTbXVWmbAgMBAAECggEACmLgu8WIRho/Z9RsFbUEUBneKN8xMi/RDFNk8gDsyK3S4q/rpVlBTkXICkH8lt052xUVksTUIIfRr5eYIcmTUHbb6uGZvvZi0x6isPWcVENrohVn5TLcrla26llDDfGWpuzNsm/4uQEGQH7ujh12A1zgOUfGjJajtYg6P7F+qDJx7pQLqP5Gxbq61Up0oc9TytA9zDrpix/USnoqfSVNF64T8DJO057mLoORMqMY/5RIxtiMoOG90QNA012LbAeBhim0FrijP55UqsdQs97REtWZ0wHL+zh8tqOm+mfkcEcn9uNE9nhOfeyzjbUfeyg0V1lkyXILWr7nd/3dDYSFMQKBgQC9OXRfPnPTJvz+iSo+OF3ZjgCgG5k0Z8EhPFQLI+WI2Q/MTrxuEo3P2I883mixmdSjpOPvEK+a5RX/YkveSxv9zAETMMRbbAKUuUYZh4oTs37NjA678QmEpGERkU4LcE/v4J/s8LPvaXBywf5XeIjhbCbypc55OxX63yWeyaBDMQKBgQC2ex15XpzZr3pQYUwce/jHFrSfcVADNDijkU6HFC4SftbEGJbkSrCpVonJRutklcBhlutWMgjSUL15EgnUt+6bDnxPPfuME/yIdoatHt3/Bg6yAjhGpPHaGOYtFST5kC0APe2cKy7oKG97nMPe+5ByUSjAUYbJVbLInUZUcFhOiwKBgGvr0uVndyPcvrplfMRT3aLxDIZEd1KeQlY0VDKuXIF6WzpJRcr5pgv/FWK/7rIsbEyRBLcaqy0Kr0siwuabq/FKYuqRC8ygg7BTIxn4ZdXqr82Hrfee97DBF+OvHfYELnM/h7bZaaaIWmv5HJjC1D7NMkF+M46NFnIoxwoTMOZhAoGAM/7srRKqetSnc5Plzg/9GS19FhmBhQgyQ1k6GP9FCXwe0g13oWEu6XGBHVsZ47VP9f682/ixzsu20XK0XmpykLgV77ZnoMhpIrEzOs0a0Hn3Yf2D7408ZLrHi30E5h+Q0wrSU7dyTDCJY52NqlHgHNLHW9VfJKtIoCVATvscDnUCgYAg6bn38qm/WDE/QPPTp2vdcw4e5Ziinz0pyK0GbclnmD8T6P/zfgUXGN3hmD03GZ8U/CazC242IJSz72B/VG6BGq2Lkqx2B6nj0ueUQA8SGmbRVOsncMxETTTi8h4qPG7hqbTubLF7ir3UG+XeIFxfVcBHV5JcdJMP0vTxOx6aIg==}
  publicKey: ${JWT_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhuHZH9hvLYEaj2Zj/ezgYH6HiFmW6QvOZR+xiyqTWGy9PgFi9YUEai241I15KCRboX2CcLASiLW4MI+l+gzJ5n4UOjYoqXBgqbWSdQubJVlARdrQrQWMc4c6nqLbqeVl3OtPH3XGES8dOHHJN0TruaJirKDMwfGOu4n+uk/QMsowq0+H9SbH4E60GChhkPQRV+G+Fy5zJAW2AZQcpZaS5WppqUJhMtjA1UvJ0KCXeclW3Kj4LPOPdvbyXEH0h/iXXZVD0HazsbBY+bkEMVolORElZE5Qet23UThppTMrkGIqbwULMDDpLyrbCb9BMl1UBW70Xz3DQJ8Tba0211VpmwIDAQAB}

logging:
  level:
    root: INFO
    com.taxidispatcher: DEBUG
    org.springframework.security: DEBUG
